name: Run Tests and Report Coverage to Code Climate

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14  # Используем официальный образ PostgreSQL
        ports:
          - 5433:5432      # Пробрасываем порт 5433 на хост (хотя по умолчанию PostgreSQL использует порт 5432)
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Set environment variables for JWT
      run: |
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
        echo "JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }}" >> $GITHUB_ENV
        echo "JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}" >> $GITHUB_ENV

    - name: Set DATABASE_URL environment variable
      run: |
        echo "DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5433/postgres" >> $GITHUB_ENV

    - name: Run Tests with Coverage
      run: |
        pytest --cov=app --cov-report=xml

    - name: Install Code Climate Reporter
      run: |
        curl -L https://github.com/codeclimate/test-reporter/releases/download/0.5.0/cc-test-reporter-0.5.0-linux-amd64 > cc-test-reporter
        chmod +x cc-test-reporter
        ./cc-test-reporter before-build
        ./cc-test-reporter upload-coverage

    - name: Upload coverage to Code Climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: ./cc-test-reporter after-build
